# MIT Licence
# Copyright 2025 feraxhp

name: Publish Web App
run-name: ğŸš€ Publish Web App ğŸš€
on:
    workflow_dispatch:
    release:
      types:
        - created

permissions:
    contents: read
    pages: write
    id-token: write
  
concurrency:
    group: "pages"
    cancel-in-progress: false
  
jobs:
  sample:
    name: ğŸ“Ÿ Deploy 2 pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:

      - name: ğŸ—ƒï¸ Checkout code
        uses: actions/checkout@v4
      
      - name: ğŸ“¦ Install npm dependencies
        shell: bash
        run: npm install
      
      - name: ğŸ§© Build lorofs
        shell: bash
        run: npm run build
        
      - name: ğŸ§© Build sample
        shell: bash
        run: cd sample && npm run build

      - name: ğŸ“¤ Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "sample/dist"

      - name: ğŸ“¡ Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: ğŸ‰ Congratulations ğŸ‰
        run: |
          echo "Your page is Up"
          echo "ğŸ‰ Congratulations ğŸ‰"

# See LICENCE in the project root
# for the full licence detail.